### ISSUE TITLE
Remove this repo?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/astrolib.coords#1]
Not being used by anything. Superseded by http://docs.astropy.org/en/stable/coordinates/index.html

**Comment by jhunkeler** [comment]
The last dangling reference in our suite is:
```
./drizzlepac/setup.cfg:	astrolib.coords (>=0.39.4)
```

**Comment by pllim** [comment]
FYI -- I did a check and wrote in https://trac.stsci.edu/ssb/stsci_python/ticket/1245 that, *"This import is commented in `tweakutils.py` and replaced with Astropy. So this dependency can be completely removed, and the commented import can be deleted."*

**Comment by pllim** [comment]
I don't see `astrolib.coords` mentioned in `drizzlepac` anymore. @SaraOgaz , I think we can archive this one as well.

**Comment by SaOgaz** [comment]
Archiving!
